In [1]:
import json
import os

raw_dir = "../data/ipl_json"

# grab the first file just to explore
sample_file = os.listdir(raw_dir)[0]
print("Looking at:", sample_file)

with open(os.path.join(raw_dir, sample_file), "r") as f:
    match = json.load(f)

print(type(match))
print(match.keys())

Looking at: 1426261.json
<class 'dict'>
dict_keys(['meta', 'info', 'innings'])

In [2]:
print(json.dumps(match["info"], indent=2))

{
  "balls_per_over": 6,
  "city": "Mohali",
  "dates": [
    "2024-04-09"
  ],
  "event": {
    "name": "Indian Premier League",
    "match_number": 23
  },
  "gender": "male",
  "match_type": "T20",
  "officials": {
    "match_referees": [
      "V Narayan Kutty"
    ],
    "reserve_umpires": [
      "PM Joshi"
    ],
    "tv_umpires": [
      "AG Wharf"
    ],
    "umpires": [
      "Navdeep Singh",
      "NA Patwardhan"
    ]
  },
  "outcome": {
    "winner": "Sunrisers Hyderabad",
    "by": {
      "runs": 2
    }
  },
  "overs": 20,
  "player_of_match": [
    "Nithish Kumar Reddy"
  ],
  "players": {
    "Sunrisers Hyderabad": [
      "TM Head",
      "Abhishek Sharma",
      "AK Markram",
      "Nithish Kumar Reddy",
      "RA Tripathi",
      "H Klaasen",
      "Abdul Samad",
      "Shahbaz Ahmed",
      "PJ Cummins",
      "B Kumar",
      "JD Unadkat",
      "T Natarajan"
    ],
    "Punjab Kings": [
      "Arshdeep Singh",
      "S Dhawan",
      "JM Bairstow",
      "P Simran Singh",
      "SM Curran",
      "Sikandar Raza",
      "Shashank Singh",
      "JM Sharma",
      "Ashutosh Sharma",
      "Harpreet Brar",
      "HV Patel",
      "K Rabada"
    ]
  },
  "registry": {
    "people": {
      "AG Wharf": "2e0fcc58",
      "AK Markram": "6a26221c",
      "Abdul Samad": "8e514b4c",
      "Abhishek Sharma": "f29185a1",
      "Arshdeep Singh": "244048f6",
      "Ashutosh Sharma": "84d9c311",
      "B Kumar": "2e81a32d",
      "H Klaasen": "235c2bb6",
      "HV Patel": "f986ca1a",
      "Harpreet Brar": "c05edf8e",
      "JD Unadkat": "1e66c162",
      "JM Bairstow": "abb83e27",
      "JM Sharma": "800d2d97",
      "K Rabada": "e62dd25d",
      "NA Patwardhan": "e6ef687d",
      "Navdeep Singh": "a3e3d8a4",
      "Nithish Kumar Reddy": "aad0c365",
      "P Simran Singh": "9418198b",
      "PJ Cummins": "ded9240e",
      "PM Joshi": "0dcc9a8c",
      "RA Tripathi": "77255a9e",
      "S Dhawan": "0a476045",
      "SM Curran": "e94915e6",
      "Shahbaz Ahmed": "f9e6e7ef",
      "Shashank Singh": "26989d80",
      "Sikandar Raza": "26d041c4",
      "T Natarajan": "ce794613",
      "TM Head": "12b610c2",
      "V Narayan Kutty": "4bacee3d"
    }
  },
  "season": "2024",
  "team_type": "club",
  "teams": [
    "Sunrisers Hyderabad",
    "Punjab Kings"
  ],
  "toss": {
    "decision": "field",
    "winner": "Punjab Kings"
  },
  "venue": "Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur"
}

In [3]:
info = match["info"]

match_row = {
    "match_id": sample_file.replace(".json", ""),
    "date": info["dates"][0],
    "city": info.get("city"),
    "venue": info["venue"],
    "team1": info["teams"][0],
    "team2": info["teams"][1],
    "toss_winner": info["toss"]["winner"],
    "toss_decision": info["toss"]["decision"],
    "winner": info["outcome"].get("winner"),
}

match_row

{'match_id': '1426261',
 'date': '2024-04-09',
 'city': 'Mohali',
 'venue': 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
 'team1': 'Sunrisers Hyderabad',
 'team2': 'Punjab Kings',
 'toss_winner': 'Punjab Kings',
 'toss_decision': 'field',
 'winner': 'Sunrisers Hyderabad'}

In [4]:
innings = match["innings"]
print(len(innings), "innings in this match")
print(innings[0].keys())
print(json.dumps(innings[0]["overs"][0], indent=2))

2 innings in this match
dict_keys(['team', 'overs', 'powerplays'])
{
  "over": 0,
  "deliveries": [
    {
      "actual_delivery": "0.1",
      "batter": "TM Head",
      "bowler": "K Rabada",
      "non_striker": "Abhishek Sharma",
      "runs": {
        "batter": 0,
        "extras": 0,
        "total": 0
      }
    },
    {
      "actual_delivery": "0.2",
      "batter": "TM Head",
      "bowler": "K Rabada",
      "non_striker": "Abhishek Sharma",
      "runs": {
        "batter": 0,
        "extras": 0,
        "total": 0
      }
    },
    {
      "actual_delivery": "0.3",
      "batter": "TM Head",
      "bowler": "K Rabada",
      "non_striker": "Abhishek Sharma",
      "runs": {
        "batter": 4,
        "extras": 0,
        "total": 4
      }
    },
    {
      "actual_delivery": "0.4",
      "batter": "TM Head",
      "bowler": "K Rabada",
      "non_striker": "Abhishek Sharma",
      "runs": {
        "batter": 0,
        "extras": 0,
        "total": 0
      }
    },
    {
      "actual_delivery": "0.5",
      "batter": "TM Head",
      "bowler": "K Rabada",
      "non_striker": "Abhishek Sharma",
      "runs": {
        "batter": 0,
        "extras": 0,
        "total": 0
      }
    },
    {
      "actual_delivery": "0.6",
      "batter": "TM Head",
      "bowler": "K Rabada",
      "non_striker": "Abhishek Sharma",
      "runs": {
        "batter": 0,
        "extras": 0,
        "total": 0
      }
    }
  ]
}

In [5]:
deliveries_rows = []

for over_data in innings[0]["overs"]:
    over_num = over_data["over"]
    for ball in over_data["deliveries"]:
        row = {
            "match_id": match_row["match_id"],
            "innings_team": innings[0]["team"],
            "over": over_num,
            "ball": ball["actual_delivery"],
            "batter": ball["batter"],
            "bowler": ball["bowler"],
            "non_striker": ball["non_striker"],
            "runs_batter": ball["runs"]["batter"],
            "runs_extras": ball["runs"]["extras"],
            "runs_total": ball["runs"]["total"],
            "is_wicket": "wickets" in ball,
        }
        deliveries_rows.append(row)

print(len(deliveries_rows), "deliveries extracted")
deliveries_rows[:3]

125 deliveries extracted

[{'match_id': '1426261',
  'innings_team': 'Sunrisers Hyderabad',
  'over': 0,
  'ball': '0.1',
  'batter': 'TM Head',
  'bowler': 'K Rabada',
  'non_striker': 'Abhishek Sharma',
  'runs_batter': 0,
  'runs_extras': 0,
  'runs_total': 0,
  'is_wicket': False},
 {'match_id': '1426261',
  'innings_team': 'Sunrisers Hyderabad',
  'over': 0,
  'ball': '0.2',
  'batter': 'TM Head',
  'bowler': 'K Rabada',
  'non_striker': 'Abhishek Sharma',
  'runs_batter': 0,
  'runs_extras': 0,
  'runs_total': 0,
  'is_wicket': False},
 {'match_id': '1426261',
  'innings_team': 'Sunrisers Hyderabad',
  'over': 0,
  'ball': '0.3',
  'batter': 'TM Head',
  'bowler': 'K Rabada',
  'non_striker': 'Abhishek Sharma',
  'runs_batter': 4,
  'runs_extras': 0,
  'runs_total': 4,
  'is_wicket': False}]

In [6]:
import pandas as pd

deliveries_df = pd.DataFrame(deliveries_rows)
deliveries_df.head()

,match_id,innings_team,over,ball,batter,bowler,non_striker,runs_batter,runs_extras,runs_total,is_wicket
0,1426261,Sunrisers Hyderabad,0,0.1,TM Head,K Rabada,Abhishek Sharma,0,0,0,False
1,1426261,Sunrisers Hyderabad,0,0.2,TM Head,K Rabada,Abhishek Sharma,0,0,0,False
2,1426261,Sunrisers Hyderabad,0,0.3,TM Head,K Rabada,Abhishek Sharma,4,0,4,False
3,1426261,Sunrisers Hyderabad,0,0.4,TM Head,K Rabada,Abhishek Sharma,0,0,0,False
4,1426261,Sunrisers Hyderabad,0,0.5,TM Head,K Rabada,Abhishek Sharma,0,0,0,False

In [7]:
deliveries_df.shape
deliveries_df.info()        # column types, nulls
deliveries_df["runs_total"].sum()   # total runs scored this innings
deliveries_df.groupby("over")["runs_total"].sum()   # runs per over — this is the seed of "powerplay runs" later

<class 'pandas.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   match_id      125 non-null    str
 1   innings_team  125 non-null    str
 2   over          125 non-null    int64
 3   ball          125 non-null    str
 4   batter        125 non-null    str
 5   bowler        125 non-null    str
 6   non_striker   125 non-null    str
 7   runs_batter   125 non-null    int64
 8   runs_extras   125 non-null    int64
 9   runs_total    125 non-null    int64
 10  is_wicket     125 non-null    bool
dtypes: bool(1), int64(4), str(6)
memory usage: 10.0 KB

over
0      4
1      6
2     16
3      2
4     11
5      1
6      7
7      9
8      5
9      5
10    15
11     9
12    10
13    11
14    22
15    13
16     6
17     4
18    15
19    11
Name: runs_total, dtype: int64

In [8]:
def extract_match_info(filepath):
    with open(filepath, "r") as f:
        match = json.load(f)
    
    info = match["info"]
    match_id = os.path.basename(filepath).replace(".json", "")
    
    outcome = info.get("outcome", {})
    
    return {
        "match_id": match_id,
        "date": info["dates"][0],
        "city": info.get("city"),
        "venue": info.get("venue"),
        "team1": info["teams"][0],
        "team2": info["teams"][1],
        "toss_winner": info.get("toss", {}).get("winner"),
        "toss_decision": info.get("toss", {}).get("decision"),
        "winner": outcome.get("winner"),
        "result": outcome.get("result"),  # e.g. "tie", "no result" — None if normal win
    }

In [9]:
def extract_deliveries(filepath):
    with open(filepath, "r") as f:
        match = json.load(f)
    
    match_id = os.path.basename(filepath).replace(".json", "")
    rows = []
    
    for inning_num, inning in enumerate(match["innings"], start=1):
        team = inning["team"]
        for over_data in inning["overs"]:
            over_num = over_data["over"]
            for ball in over_data["deliveries"]:
                rows.append({
                    "match_id": match_id,
                    "innings": inning_num,
                    "innings_team": team,
                    "over": over_num,
                    "ball": ball["actual_delivery"],
                    "batter": ball["batter"],
                    "bowler": ball["bowler"],
                    "non_striker": ball["non_striker"],
                    "runs_batter": ball["runs"]["batter"],
                    "runs_extras": ball["runs"]["extras"],
                    "runs_total": ball["runs"]["total"],
                    "is_wicket": "wickets" in ball,
                })
    
    return rows

In [10]:
sample_path = os.path.join(raw_dir, sample_file)

info_test = extract_match_info(sample_path)
deliveries_test = extract_deliveries(sample_path)

print(info_test)
print(len(deliveries_test), "deliveries")

{'match_id': '1426261', 'date': '2024-04-09', 'city': 'Mohali', 'venue': 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur', 'team1': 'Sunrisers Hyderabad', 'team2': 'Punjab Kings', 'toss_winner': 'Punjab Kings', 'toss_decision': 'field', 'winner': 'Sunrisers Hyderabad', 'result': None}
251 deliveries

In [11]:
all_files = [f for f in os.listdir(raw_dir) if f.endswith(".json")]
print(len(all_files), "match files found")

1243 match files found

In [12]:
all_matches = []
all_deliveries = []
failed_files = []

for filename in all_files:
    filepath = os.path.join(raw_dir, filename)
    try:
        match_info = extract_match_info(filepath)
        match_deliveries = extract_deliveries(filepath)
        
        all_matches.append(match_info)
        all_deliveries.extend(match_deliveries)
    except Exception as e:
        failed_files.append((filename, str(e)))

print(f"Successfully processed: {len(all_matches)} matches")
print(f"Failed: {len(failed_files)} files")
if failed_files:
    print(failed_files[:5])  # show first few failures

Successfully processed: 1243 matches
Failed: 0 files

In [13]:
matches_df = pd.DataFrame(all_matches)
deliveries_df = pd.DataFrame(all_deliveries)

print(matches_df.shape)
print(deliveries_df.shape)

matches_df.head()

(1243, 10)
(295732, 12)

,match_id,date,city,venue,team1,team2,toss_winner,toss_decision,winner,result
0,1426261,2024-04-09,Mohali,Maharaja Yadavindra Singh International Cricke...,Sunrisers Hyderabad,Punjab Kings,Punjab Kings,field,Sunrisers Hyderabad,NaN
1,1359507,2023-04-23,Kolkata,"Eden Gardens, Kolkata",Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,Chennai Super Kings,NaN
2,392217,2009-05-09,Kimberley,De Beers Diamond Oval,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,bat,Chennai Super Kings,NaN
3,1254112,2021-10-02,Sharjah,Sharjah Cricket Stadium,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Delhi Capitals,NaN
4,829817,2015-05-19,Mumbai,Wankhede Stadium,Chennai Super Kings,Mumbai Indians,Mumbai Indians,bat,Mumbai Indians,NaN

In [14]:
matches_df.isnull().sum()

match_id            0
date                0
city               51
venue               0
team1               0
team2               0
toss_winner         0
toss_decision       0
winner             25
result           1218
dtype: int64

In [15]:
matches_df.to_csv("../data/processed/matches.csv", index=False)
deliveries_df.to_csv("../data/processed/deliveries.csv", index=False)

print("Saved!")

Saved!

In [16]:
matches_df["date"] = pd.to_datetime(matches_df["date"])
matches_df = matches_df.sort_values("date").reset_index(drop=True)
matches_df.head()

,match_id,date,city,venue,team1,team2,toss_winner,toss_decision,winner,result
0,335982,2008-04-18,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,NaN
1,335983,2008-04-19,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,NaN
2,335984,2008-04-19,Delhi,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,NaN
3,335986,2008-04-20,Kolkata,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,NaN
4,335985,2008-04-20,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,NaN

In [17]:
matches_df.to_csv("../data/processed/matches.csv", index=False)

In [18]:
matches_df[matches_df["city"].isnull()]["result"].value_counts()

result
tie    3
Name: count, dtype: int64

In [19]:
matches_df[matches_df["city"].isnull()][["match_id", "venue", "date"]].head(10)

    match_id                                venue       date
399   729281              Sharjah Cricket Stadium 2014-04-17
402   729287  Dubai International Cricket Stadium 2014-04-19
403   729289  Dubai International Cricket Stadium 2014-04-19
404   729291              Sharjah Cricket Stadium 2014-04-20
406   729295              Sharjah Cricket Stadium 2014-04-22
407   729297  Dubai International Cricket Stadium 2014-04-23
408   729299              Sharjah Cricket Stadium 2014-04-24
409   729303  Dubai International Cricket Stadium 2014-04-25
410   729301  Dubai International Cricket Stadium 2014-04-25
413   729311              Sharjah Cricket Stadium 2014-04-27

In [20]:
venue_to_city = {
    "Sharjah Cricket Stadium": "Sharjah",
    "Dubai International Cricket Stadium": "Dubai",
}

matches_df["city"] = matches_df["city"].fillna(matches_df["venue"].map(venue_to_city))

matches_df["city"].isnull().sum()

np.int64(0)

In [21]:
matches_df[matches_df["city"].isnull()][["match_id", "venue", "date"]]

Empty DataFrame
Columns: [match_id, venue, date]
Index: []

In [22]:
matches_df.isnull().sum()

match_id            0
date                0
city                0
venue               0
team1               0
team2               0
toss_winner         0
toss_decision       0
winner             25
result           1218
dtype: int64

In [23]:
matches_df["result"] = matches_df["result"].fillna("normal")
matches_df["result"].value_counts()

result
normal       1218
tie            16
no result       9
Name: count, dtype: int64

In [24]:
matches_df.to_csv("../data/processed/matches.csv", index=False)